import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak
)
from reportlab.lib import colors
import openpyxl
from openpyxl.styles import Font, PatternFill, Border, Side, Alignment

def _section_divider():
    return HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceAfter=8, spaceBefore=4)

def _build_styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("ReportTitle", parent=base["Title"], fontSize=18, leading=22, spaceAfter=8),
        "heading1": ParagraphStyle("H1", parent=base["Heading1"], fontSize=14, leading=18, spaceBefore=12, spaceAfter=6, textColor=colors.HexColor("#1e3a8a")),
        "heading2": ParagraphStyle("H2", parent=base["Heading2"], fontSize=12, leading=14, spaceBefore=8, spaceAfter=4, textColor=colors.HexColor("#2563eb")),
        "body": ParagraphStyle("BodyText", parent=base["BodyText"], fontSize=9, leading=13, spaceAfter=4),
        "bullet": ParagraphStyle("Bullet", parent=base["BodyText"], fontSize=9, leading=13, leftIndent=15, spaceAfter=2, bulletIndent=5),
        "fallback": ParagraphStyle("Fallback", parent=base["Italic"], fontSize=9, textColor=colors.grey),
    }

def generate_real_time_pdf(ad: dict, output_path: str):
    styles = _build_styles()
    doc = SimpleDocTemplate(output_path, pagesize=A4, topMargin=15*mm, bottomMargin=15*mm, leftMargin=15*mm, rightMargin=15*mm)
    elements = []

    framework = ad.get("framework", "Assessment")
    company_name = ad.get("company_name", "Unknown Organization")
    elements.append(Paragraph(f"{company_name} - {framework} Assessment Report", styles["title"]))
    elements.append(Paragraph("Generated by Aegis.One GRC System", styles["fallback"]))
    elements.append(_section_divider())

    if ad.get("executive_summary"):
        elements.append(Paragraph("Executive Summary", styles["heading1"]))
        elements.append(Paragraph(str(ad.get("executive_summary")), styles["body"]))
        elements.append(Spacer(1, 10))

    elements.append(Paragraph("Assessment Scorecard", styles["heading1"]))
    score = ad.get("compliance_score", 0)
    rows = [
        ["Compliance Score", f"{score}%"],
        ["Total Controls", str(ad.get("total_controls", 0))],
        ["Compliant", str(ad.get("compliant_controls", 0))],
        ["Partial", str(ad.get("partial_controls", 0))],
        ["Missing", str(ad.get("missing_controls", 0))],
    ]
    t = Table(rows, colWidths=[80*mm, 40*mm])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 10))

    if ad.get("insights"):
        elements.append(Paragraph("Actionable Insights", styles["heading1"]))
        for ins in ad["insights"]:
            elements.append(Paragraph(f"• {ins}", styles["bullet"]))
        elements.append(Spacer(1, 10))

    gaps = ad.get("critical_gaps", [])
    if gaps:
        elements.append(Paragraph("Critical Gaps (Missing Requirements)", styles["heading1"]))
        gap_rows = [["Control", "Requirement", "Section", "Severity"]]
        for gap in gaps:
            gap_rows.append([
                gap.get("control_id", ""),
                Paragraph(gap.get("requirement", ""), styles["body"]),
                gap.get("section", ""),
                gap.get("severity", "")
            ])
        gt = Table(gap_rows, colWidths=[25*mm, 90*mm, 20*mm, 20*mm], repeatRows=1)
        gt.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(gt)

    elements.append(PageBreak())

    def _add_table_section(title, data, headers, dict_keys, col_widths):
        if not data: return
        elements.append(Paragraph(title, styles["heading1"]))
        t_rows = [headers]
        for row in data:
            t_rows.append([Paragraph(str(row.get(k, "")), styles["body"]) for k in dict_keys])
        tbl = Table(t_rows, colWidths=col_widths, repeatRows=1)
        tbl.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(tbl)
        elements.append(Spacer(1, 10))

    risk_reg = ad.get("risk_register", [])
    if isinstance(risk_reg, dict): risk_reg = risk_reg.get("entries", [])
    if risk_reg:
        _add_table_section(
            "Risk Register", risk_reg,
            ["Risk ID", "Risk Name", "Impact", "Likelihood", "Score", "Level"],
            ["risk_id", "risk_name", "impact", "likelihood", "score", "level"],
            [20*mm, 60*mm, 20*mm, 20*mm, 20*mm, 20*mm]
        )

    treat_plan = ad.get("treatment_plan", [])
    if isinstance(treat_plan, dict): treat_plan = treat_plan.get("actions", [])
    if treat_plan:
        _add_table_section(
            "Treatment Plan", treat_plan,
            ["Priority", "Action", "Cost", "Effort", "Timeline"],
            ["priority", "action", "cost", "effort", "timeline"],
            [20*mm, 60*mm, 20*mm, 30*mm, 30*mm]
        )

    soa_data = ad.get("soa", [])
    if isinstance(soa_data, dict): soa_data = soa_data.get("entries", [])
    if soa_data:
        elements.append(PageBreak())
        _add_table_section(
            "Statement of Applicability (SoA)", soa_data,
            ["Control", "Title", "Applicable", "Impl."],
            ["control_no", "control_title", "applicable", "implementation"],
            [25*mm, 85*mm, 20*mm, 30*mm]
        )

    comp_matrix = ad.get("compliance_matrix", {})
    comp_entries = comp_matrix.get("entries", []) if isinstance(comp_matrix, dict) else comp_matrix
    if comp_entries:
        elements.append(PageBreak())
        _add_table_section(
            "Compliance Matrix", comp_entries,
            ["ID", "Requirement", "Severity", "Status"],
            ["control_id", "requirement", "severity", "status"],
            [20*mm, 100*mm, 20*mm, 20*mm]
        )

    doc.build(elements)


def generate_real_time_excel(ad: dict, output_path: str):
    wb = openpyxl.Workbook()
    # Remove default sheet
    wb.remove(wb.active)

    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="1F497D", end_color="1F497D", fill_type="solid")
    border = Border(left=Side(style='thin'), right=Side(style='thin'), top=Side(style='thin'), bottom=Side(style='thin'))

    def auto_adjust_width(ws):
        for col in ws.columns:
            max_len = max((len(str(val)) for val in [cell.value for cell in col] if val is not None), default=0)
            adjusted_width = (max_len + 2)
            if adjusted_width > 50: adjusted_width = 50
            ws.column_dimensions[col[0].column_letter].width = adjusted_width

    def add_sheet(title, data, keys, headers):
        if not data: return
        ws = wb.create_sheet(title=title)
        ws.append(headers)
        for cell in ws[1]:
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center")
        for row in data:
            ws.append([str(row.get(k, "")) for k in keys])
        for row in ws.iter_rows():
            for cell in row:
                cell.border = border
                cell.alignment = Alignment(vertical="top", wrap_text=True)
        auto_adjust_width(ws)

    # 1. Summary Sheet
    ws_sum = wb.create_sheet(title="Summary")
    ws_sum.append(["Metric", "Value"])
    for cell in ws_sum[1]: cell.font = header_font; cell.fill = header_fill
    score = ad.get("compliance_score", 0)
    ws_sum.append(["Framework", ad.get("framework", "")])
    ws_sum.append(["Compliance Score", f"{score}%"])
    ws_sum.append(["Total Controls", ad.get("total_controls", 0)])
    ws_sum.append(["Compliant Controls", ad.get("compliant_controls", 0)])
    ws_sum.append(["Partial Controls", ad.get("partial_controls", 0)])
    ws_sum.append(["Missing Controls", ad.get("missing_controls", 0)])
    for row in ws_sum.iter_rows():
        for cell in row:
            cell.border = border
            cell.alignment = Alignment(vertical="top")
    auto_adjust_width(ws_sum)

    # 2. Risk Register
    risk_reg = ad.get("risk_register", [])
    if isinstance(risk_reg, dict): risk_reg = risk_reg.get("entries", [])
    if risk_reg:
        add_sheet(
            "Risk Register", risk_reg,
            ["risk_id", "risk_name", "impact", "likelihood", "score", "level"],
            ["Risk ID", "Risk Name", "Impact", "Likelihood", "Score", "Level"]
        )

    # 3. Treatment Plan
    treat_plan = ad.get("treatment_plan", [])
    if isinstance(treat_plan, dict): treat_plan = treat_plan.get("actions", [])
    if treat_plan:
        add_sheet(
            "Treatment Plan", treat_plan,
            ["risk_id", "priority", "action", "cost", "effort", "timeline"],
            ["Risk ID", "Priority", "Action", "Cost", "Effort", "Timeline"]
        )

    # 4. SoA
    soa_data = ad.get("soa", [])
    if isinstance(soa_data, dict): soa_data = soa_data.get("entries", [])
    if soa_data:
        add_sheet(
            "SoA", soa_data,
            ["section", "control_no", "control_title", "applicable", "remarks", "implementation", "reference"],
            ["Section", "Control No", "Control Title", "Applicable", "Remarks", "Implementation", "Reference"]
        )

    # 5. Compliance Matrix
    comp_matrix = ad.get("compliance_matrix", {})
    comp_entries = comp_matrix.get("entries", []) if isinstance(comp_matrix, dict) else comp_matrix
    if comp_entries:
        add_sheet(
            "Compliance Matrix", comp_entries,
            ["control_id", "requirement", "section", "severity", "status"],
            ["Control ID", "Requirement", "Section", "Severity", "Status"]
        )

    wb.save(output_path)
